# Generated by Django 6.0.6 on 2026-06-22 18:26

from django.db import migrations

import agentproof_backend.apps.accounts.managers


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", agentproof_backend.apps.accounts.managers.UserManager()),
            ],
        ),
    ]
