# Generated by Django 6.0.6 on 2026-07-06 07:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0002_alter_environment_options_alter_project_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_trace_id", models.CharField(max_length=160)),
                ("schema_version", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("partial", "Partial"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("input", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("error_type", models.CharField(blank=True, max_length=160)),
                ("error_message", models.TextField(blank=True)),
                ("total_input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ("user_identifier", models.CharField(blank=True, max_length=200)),
                ("session_identifier", models.CharField(blank=True, db_index=True, max_length=200)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="traces", to="projects.environment"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traces",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="traces", to="projects.project"
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at", "-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Span",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_span_id", models.CharField(max_length=160)),
                ("parent_external_span_id", models.CharField(blank=True, max_length=160)),
                (
                    "span_type",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("model", "Model"),
                            ("tool", "Tool"),
                            ("retrieval", "Retrieval"),
                            ("guardrail", "Guardrail"),
                            ("workflow", "Workflow"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error"), ("unset", "Unset")],
                        db_index=True,
                        default="unset",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("input", models.JSONField(blank=True, default=dict)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("error_type", models.CharField(blank=True, max_length=160)),
                ("error_message", models.TextField(blank=True)),
                ("provider_name", models.CharField(blank=True, max_length=120)),
                ("model_name", models.CharField(blank=True, max_length=160)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spans",
                        to="organizations.organization",
                    ),
                ),
                (
                    "trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="spans", to="telemetry.trace"
                    ),
                ),
            ],
            options={
                "ordering": ("started_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="TraceAnnotation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("annotation_type", models.CharField(max_length=80)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trace_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_annotations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="annotations", to="telemetry.trace"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SpanEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="span_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "span",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="telemetry.span"
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
                "indexes": [
                    models.Index(fields=["span", "occurred_at"], name="span_event_time_idx"),
                    models.Index(fields=["organization", "name"], name="span_event_org_name_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(
                fields=["organization", "project", "environment", "-started_at"], name="trace_scope_started_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(fields=["organization", "external_trace_id"], name="trace_org_external_idx"),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(fields=["organization", "status", "-started_at"], name="trace_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="trace",
            index=models.Index(fields=["project", "session_identifier"], name="trace_project_session_idx"),
        ),
        migrations.AddConstraint(
            model_name="trace",
            constraint=models.UniqueConstraint(
                fields=("organization", "environment", "external_trace_id", "schema_version"),
                name="unique_trace_identity_per_env",
            ),
        ),
        migrations.AddConstraint(
            model_name="trace",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["success", "error", "partial", "unknown"])),
                name="trace_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="trace",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_ms__isnull", True), ("duration_ms__gte", 0), _connector="OR"),
                name="trace_duration_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="span",
            index=models.Index(fields=["trace", "parent_external_span_id"], name="span_trace_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="span",
            index=models.Index(fields=["organization", "span_type", "-started_at"], name="span_org_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="span",
            constraint=models.UniqueConstraint(
                fields=("trace", "external_span_id"), name="unique_span_identity_per_trace"
            ),
        ),
        migrations.AddConstraint(
            model_name="span",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("span_type__in", ["agent", "model", "tool", "retrieval", "guardrail", "workflow", "custom"])
                ),
                name="span_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="span",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["success", "error", "unset"])), name="span_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="span",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_ms__isnull", True), ("duration_ms__gte", 0), _connector="OR"),
                name="span_duration_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="traceannotation",
            index=models.Index(fields=["organization", "annotation_type"], name="annotation_org_type_idx"),
        ),
        migrations.AddIndex(
            model_name="traceannotation",
            index=models.Index(fields=["trace", "-created_at"], name="annotation_trace_time_idx"),
        ),
    ]
