# Generated by Django 6.0.6 on 2026-06-25 06:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=63)),
                ("description", models.TextField(blank=True)),
                (
                    "capture_mode",
                    models.CharField(
                        choices=[("metadata_only", "Metadata only"), ("redacted", "Redacted"), ("full", "Full")],
                        default="redacted",
                        max_length=32,
                    ),
                ),
                ("retention_days", models.PositiveIntegerField(default=30)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=63)),
                (
                    "environment_type",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("custom", "Custom"),
                        ],
                        default="development",
                        max_length=32,
                    ),
                ),
                (
                    "capture_mode_override",
                    models.CharField(
                        blank=True,
                        choices=[("metadata_only", "Metadata only"), ("redacted", "Redacted"), ("full", "Full")],
                        max_length=32,
                    ),
                ),
                ("retention_days_override", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="environments", to="projects.project"
                    ),
                ),
            ],
            options={
                "ordering": ("project__name", "name"),
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["organization", "slug"], name="project_org_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["organization", "name"], name="project_org_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(fields=("organization", "slug"), name="unique_project_slug_per_org"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("capture_mode__in", ["metadata_only", "redacted", "full"])),
                name="project_capture_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_days__gte", 1)), name="project_retention_days_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="environment",
            index=models.Index(fields=["organization", "slug"], name="env_org_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="environment",
            index=models.Index(fields=["project", "slug"], name="env_project_slug_idx"),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.UniqueConstraint(fields=("project", "slug"), name="unique_environment_slug_per_project"),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.CheckConstraint(
                condition=models.Q(("environment_type__in", ["development", "staging", "production", "custom"])),
                name="environment_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capture_mode_override", ""),
                    ("capture_mode_override__in", ["metadata_only", "redacted", "full"]),
                    _connector="OR",
                ),
                name="environment_capture_override_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retention_days_override__isnull", True), ("retention_days_override__gte", 1), _connector="OR"
                ),
                name="environment_retention_override_positive",
            ),
        ),
    ]
