# Generated by Django 6.0.6 on 2026-06-29 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environment",
            options={"ordering": ("project__name", "name", "id")},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("name", "id")},
        ),
        migrations.RemoveConstraint(
            model_name="environment",
            name="environment_capture_override_valid",
        ),
        migrations.RemoveConstraint(
            model_name="environment",
            name="environment_retention_override_positive",
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="project_retention_days_positive",
        ),
        migrations.RemoveIndex(
            model_name="environment",
            name="env_org_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="environment",
            name="env_project_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_org_slug_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_org_name_idx",
        ),
        migrations.AddField(
            model_name="environment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_environments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], db_index=True, default="active", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")], db_index=True, default="active", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="capture_mode_override",
            field=models.CharField(
                blank=True,
                choices=[("metadata_only", "Metadata only"), ("redacted", "Redacted"), ("full", "Full")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="environment_type",
            field=models.CharField(
                choices=[
                    ("development", "Development"),
                    ("staging", "Staging"),
                    ("production", "Production"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="environment",
            name="retention_days_override",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="environment",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=63),
        ),
        migrations.AlterField(
            model_name="project",
            name="capture_mode",
            field=models.CharField(
                choices=[("metadata_only", "Metadata only"), ("redacted", "Redacted"), ("full", "Full")],
                default="redacted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="retention_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=63),
        ),
        migrations.AddIndex(
            model_name="environment",
            index=models.Index(fields=["organization", "status"], name="environment_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="environment",
            index=models.Index(fields=["project", "status", "environment_type"], name="environment_project_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["organization", "status", "name"], name="project_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["organization", "created_at"], name="project_org_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])), name="environment_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capture_mode_override", ""),
                    ("capture_mode_override__isnull", True),
                    ("capture_mode_override__in", ["metadata_only", "redacted", "full"]),
                    _connector="OR",
                ),
                name="environment_capture_override_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retention_days_override__isnull", True),
                    models.Q(("retention_days_override__gte", 1), ("retention_days_override__lte", 3650)),
                    _connector="OR",
                ),
                name="environment_retention_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])), name="project_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_days__gte", 1), ("retention_days__lte", 3650)),
                name="project_retention_valid",
            ),
        ),
    ]
