# Generated by Django 6.0.6 on 2026-07-07 07:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("aggregate_type", models.CharField(max_length=120)),
                ("aggregate_id", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at", "created_at"], name="outbox_ready_idx"),
                    models.Index(fields=["status", "locked_at"], name="outbox_locked_idx"),
                    models.Index(
                        fields=["organization", "event_type", "created_at"], name="outbox_org_type_created_idx"
                    ),
                    models.Index(fields=["aggregate_type", "aggregate_id"], name="outbox_aggregate_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "publishing", "published", "failed"])),
                        name="outbox_event_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__gte", 0)), name="outbox_attempt_count_non_negative"
                    ),
                ],
            },
        ),
    ]
